apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: online-boutique-monitor
  namespace: lgtm-fresh
  labels:
    release: base-monitoring
spec:
  selector:
    matchLabels:
      app: frontend # Bạn có thể lặp lại cho các app khác hoặc dùng matchExpressions
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
